### ISSUE TITLE
Runtime assertion when simplifying mesh on Linux

### ISSUE THREAD

**Issue by mjrister** [mjrister/mesh-simplification#1]
### Problem Summary

On Linux, simplifying a mesh with many vertices will crash due to hash collisions when constructing a half-edge mesh. 

### Impact

- [X] Is this problem user facing?
- [ ] Is there a known workaround?
- [ ] Is this a regression?

### Repro Steps

1. Run the program with the assets/models/bunny.obj model
2. Press the 'S' key.

### Expected Result

The mesh is correctly simplified

### Actual Result

An assertion is triggered in debug mode or the program crashes with a segfault in release mode.

### Environment

Ubuntu 22.04.3 LTS
Clang 17.0.4
OpenGL core profile version string: 4.1 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL core profile shading language version string: 4.10

### Log Output

```shell
OpenGL version: 4.5 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1, GLSL version: 4.50
mesh_simplification: /home/matthew-rister/.vs/mesh-simplification/src/geometry/half_edge_mesh.cpp:43: std::shared_ptr<qem::HalfEdge> (anonymous namespace)::CreateHalfEdge(const st
```

**Comment by matthew-rister** [comment]
This was confirmed to be related to hash collisions by changing values in `hash_value` in `src/geometry/vertex.h` which successfully simplified the model one time, but crashed on the second iteration. This issue requires further investigation into a more robust hash algorithm.

**Comment by matthew-rister** [comment]
As an aside, fixing this might also enable reinstating x86 builds.

**Comment by Nettal** [comment]
hi Matthew, consider use std::unordered_map with _Hash _Pred  Template?
I implemented mesh simplification based on your mesh-simplification.
there is my implemention that uses  unordered_map with _Hash _Pred Template [https://github.com/Nettal/mesh-simplification/blob/7bb0b82918e0f15ec1a386aefbcc5728802ecadb/src/geometry/include/geometry/half_edge_mesh.h#L29](url)
